import Container from "./components/Container";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen">
        <Container>
          <Navbar />
          {children}
        </Container>
      </body>
    </html>
  );
}
